firstProject-web/src/main/java/manageBean/UserBean.java
package manageBean;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import java.util.Random;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.servlet.http.HttpSession;

import persistence.Client;
import persistence.Reclamation;
import persistence.User;
import service.BasicOpsLocal;

@ManagedBean
@ViewScoped
public class UserBean implements Serializable {
	private static final long serialVersionUID = 1L;
	@EJB
	private BasicOpsLocal basicOpsLocal;
	private boolean formDisplayed = false;
	private boolean formDis1 = false ;
	
	private int id;
	private String name;
	private String login;
	private String password;
	private String email;
	private Integer User_Reclame;
	private String description;
	private String type;
	private String degres;
	private String statut;
	private String statut_user;
	private int id_reclam;
	private List<User> users ;
	private List<String> rest; 
	private List<Reclamation> reclamations;
	FacesContext facesContext = FacesContext.getCurrentInstance();
	HttpSession session = (HttpSession)facesContext.getExternalContext().getSession(true);
    private User currentUser = (User)session.getAttribute("currentSessionUser");
    Identity idu = new Identity();
	private User user = new User();
	private List<Integer> simpleList;
	final String username = "consimitounsi@gmail.com";
    final String passwordEmail = "consomitounsi";
    private int k;
	
	
	@PostConstruct
	public void init(){		
		currentUser = (User)session.getAttribute("currentSessionUser");
		
		Map<String, String> params =FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
		String parameterOne = params.get("id");
		if(parameterOne != null) {
		id_reclam = Integer.parseInt(parameterOne);
		}
		}
       
	public String doReclamation(int id) {
		currentUser = (User)session.getAttribute("currentSessionUser");
		String navigateTo = "";
				FacesContext facesContext = FacesContext.getCurrentInstance();
				 HttpSession session = (HttpSession)facesContext.getExternalContext().getSession(true);       					
				navigateTo = "/pages/reclamation/reclamation?faces-redirect=true&id=" + id;

		 
		return navigateTo;
	}

	
	
	
	
	public List<Reclamation> getAllReclamation() {
		reclamations = basicOpsLocal.findAllReclamations();
		return reclamations;
		}
	
	public List<User> getAllUser() {
		users = basicOpsLocal.findAllUsers();
		return users;
		}
	
	
	public void removeReclamation(Reclamation reclamation) {
basicOpsLocal.removeReclamation(reclamation);

reclamations = basicOpsLocal.findAllReclamations();
     	formDisplayed = true;
	}
	
public String doaddReclamation(){
	currentUser = (User)session.getAttribute("currentSessionUser");
	basicOpsLocal.ajouterRecalamation(new Reclamation(id_reclam, description, type, degres, "non traité", currentUser));
    formDisplayed = true;
	String navigateTo = "";
	FacesContext facesContext = FacesContext.getCurrentInstance();
	 HttpSession session = (HttpSession)facesContext.getExternalContext().getSession(true);       					
	navigateTo = "/pages/reclamation/listUser?faces-redirect=true";
	return navigateTo;
		
	}
public void updateReclamation(Reclamation reclamation)
{ 
	reclamation.setStatut("approuver");
	k = basicOpsLocal.getnbpostbypost(reclamation.getUser_Reclame());
	if(k>=5) {
		User user = basicOpsLocal.findUser(reclamation.getUser_Reclame());
		user.setStatut("invalide");
		basicOpsLocal.updateUser(user);
		users = basicOpsLocal.findAllUsers();
	}

basicOpsLocal.updateReclamation(reclamation);
Properties props = new Properties();
props.put("mail.smtp.auth", "true");
props.put("mail.smtp.starttls.enable", "true");
props.put("mail.smtp.host", "smtp.gmail.com");
props.put("mail.smtp.port", "587");
Session session = Session.getInstance(props,
        new javax.mail.Authenticator() {
          protected PasswordAuthentication getPasswordAuthentication() {
              return new PasswordAuthentication(username, passwordEmail);
          }
        });

      try {

          Message message = new MimeMessage(session);
          message.setFrom(new InternetAddress("consimitounsi@gmail.com"));
          message.setRecipients(Message.RecipientType.TO,
              InternetAddress.parse(reclamation.getUser().getEmail()));
          message.setSubject("Reponse reclamation");
          message.setText("votre reclamation a été approuver"
              + "\n\n No spam to my email, please!");

          Transport.send(message);

          System.out.println("Done");

      } catch (MessagingException e) {
          throw new RuntimeException(e);
      }

}

public void rejeterReclamation(Reclamation reclamation)
{ 
	reclamation.setStatut("rejeter");
	
basicOpsLocal.updateReclamation(reclamation);
Properties props = new Properties();
props.put("mail.smtp.auth", "true");
props.put("mail.smtp.starttls.enable", "true");
props.put("mail.smtp.host", "smtp.gmail.com");
props.put("mail.smtp.port", "587");
Session session = Session.getInstance(props,
        new javax.mail.Authenticator() {
          protected PasswordAuthentication getPasswordAuthentication() {
              return new PasswordAuthentication(username, passwordEmail);
          }
        });

      try {

          Message message = new MimeMessage(session);
          message.setFrom(new InternetAddress("consimitounsi@gmail.com"));
          message.setRecipients(Message.RecipientType.TO,
              InternetAddress.parse(reclamation.getUser().getEmail()));
          message.setSubject("Reponse reclamation");
          message.setText("votre reclamation a été rejeter"
              + "\n\n No spam to my email, please!");

          Transport.send(message);

          System.out.println("Done");

      } catch (MessagingException e) {
          throw new RuntimeException(e);
      }
}
	

	public Identity getIdu() {
		return idu;
	}

	public void setIdu(Identity idu) {
		this.idu = idu;
	}

	public Integer getUser_Reclame() {
		return User_Reclame;
	}



	public void setUser_Reclame(Integer user_Reclame) {
		User_Reclame = user_Reclame;
	}



	public String getDescription() {
		return description;
	}



	public void setDescription(String description) {
		this.description = description;
	}



	public String getType() {
		return type;
	}



	public void setType(String type) {
		this.type = type;
	}



	public String getDegres() {
		return degres;
	}


	

	public String getStatut_user() {
		return statut_user;
	}

	public void setStatut_user(String statut_user) {
		this.statut_user = statut_user;
	}

	public void setDegres(String degres) {
		this.degres = degres;
	}



	public String getStatut() {
		return statut;
	}



	public void setStatut(String statut) {
		this.statut = statut;
	}



	public List<Reclamation> getReclamations() {
		return reclamations;
	}



	public void setReclamations(List<Reclamation> reclamations) {
		this.reclamations = reclamations;
	}



	public BasicOpsLocal getBasicOpsLocal() {
		return basicOpsLocal;
	}


	public void setBasicOpsLocal(BasicOpsLocal basicOpsLocal) {
		this.basicOpsLocal = basicOpsLocal;
	}


	public boolean isFormDisplayed() {
		return formDisplayed;
	}

	

	public int getK() {
		return k;
	}

	public void setK(int k) {
		this.k = k;
	}

	public void setFormDisplayed(boolean formDisplayed) {
		this.formDisplayed = formDisplayed;
	}
	
	


	public FacesContext getFacesContext() {
		return facesContext;
	}

	public void setFacesContext(FacesContext facesContext) {
		this.facesContext = facesContext;
	}

	public HttpSession getSession() {
		return session;
	}

	public void setSession(HttpSession session) {
		this.session = session;
	}

	public User getCurrentUser() {
		return currentUser;
	}

	public void setCurrentUser(User currentUser) {
		this.currentUser = currentUser;
	}

	public boolean isFormDis1() {
		return formDis1;
	}


	public void setFormDis1(boolean formDis1) {
		this.formDis1 = formDis1;
	}


	public int getId() {
		return id;
	}


	public void setId(int id) {
		this.id = id;
	}


	public String getName() {
		return name;
	}


	public void setName(String name) {
		this.name = name;
	}


	public String getLogin() {
		return login;
	}


	public void setLogin(String login) {
		this.login = login;
	}


	public String getPassword() {
		return password;
	}


	public void setPassword(String password) {
		this.password = password;
	}


	public String getEmail() {
		return email;
	}


	public void setEmail(String email) {
		this.email = email;
	}


	public List<User> getUsers() {
		return users;
	}


	public void setUsers(List<User> users) {
		this.users = users;
	}


	public List<String> getRest() {
		return rest;
	}


	public void setRest(List<String> rest) {
		this.rest = rest;
	}


	


	public static long getSerialversionuid() {
		return serialVersionUID;
	}
	
	
	
	

}

firstProject-web/src/main/java/manageBean/statBean.java
package manageBean;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import java.util.Random;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.servlet.http.HttpSession;

import persistence.Client;
import persistence.Reclamation;
import persistence.User;
import service.BasicOpsLocal;

@ManagedBean
@ViewScoped
public class statBean {
	private static final long serialVersionUID = 1L;
	@EJB
	private BasicOpsLocal basicOpsLocal;
	private boolean formDisplayed = false;
	private boolean formDis1 = false ;
	
	private int id;
	private String name;
	private String login;
	private String password;
	private String email;
	private Integer User_Reclame;
	private String description;
	private String type;
	private String degres;
	private String statut;
	private String statut_user;
	private int id_reclam;
	private List<User> users ;
	private List<String> rest; 
	private List<Reclamation> reclamations;
	private int reclamationsApp;
	private int reclamationsRej;
	FacesContext facesContext = FacesContext.getCurrentInstance();
	HttpSession session = (HttpSession)facesContext.getExternalContext().getSession(true);
    private User currentUser = (User)session.getAttribute("currentSessionUser");
    Identity idu = new Identity();
	private User user = new User();
	final String username = "consimitounsi@gmail.com";
    final String passwordEmail = "consomitounsi";
    private int k;
	
	
	@PostConstruct
	public void init(){	
				reclamationsApp = basicOpsLocal.findAllReclamationsApp();
				reclamationsRej = basicOpsLocal.findAllReclamationsRej();
		currentUser = (User)session.getAttribute("currentSessionUser");
		Map<String, String> params =FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
		}
	
	public void getAllReclamation() {
		
		}
	
	public Identity getIdu() {
		return idu;
	}

	public void setIdu(Identity idu) {
		this.idu = idu;
	}

	public Integer getUser_Reclame() {
		return User_Reclame;
	}



	public void setUser_Reclame(Integer user_Reclame) {
		User_Reclame = user_Reclame;
	}



	public String getDescription() {
		return description;
	}



	public void setDescription(String description) {
		this.description = description;
	}



	public String getType() {
		return type;
	}



	public void setType(String type) {
		this.type = type;
	}



	public String getDegres() {
		return degres;
	}


	

	public String getStatut_user() {
		return statut_user;
	}

	public void setStatut_user(String statut_user) {
		this.statut_user = statut_user;
	}

	public void setDegres(String degres) {
		this.degres = degres;
	}



	public String getStatut() {
		return statut;
	}



	public void setStatut(String statut) {
		this.statut = statut;
	}



	public List<Reclamation> getReclamations() {
		return reclamations;
	}



	public void setReclamations(List<Reclamation> reclamations) {
		this.reclamations = reclamations;
	}



	public BasicOpsLocal getBasicOpsLocal() {
		return basicOpsLocal;
	}


	public void setBasicOpsLocal(BasicOpsLocal basicOpsLocal) {
		this.basicOpsLocal = basicOpsLocal;
	}


	public boolean isFormDisplayed() {
		return formDisplayed;
	}

	

	public int getK() {
		return k;
	}

	public void setK(int k) {
		this.k = k;
	}

	public void setFormDisplayed(boolean formDisplayed) {
		this.formDisplayed = formDisplayed;
	}
	
	


	public FacesContext getFacesContext() {
		return facesContext;
	}

	public void setFacesContext(FacesContext facesContext) {
		this.facesContext = facesContext;
	}

	public HttpSession getSession() {
		return session;
	}

	public void setSession(HttpSession session) {
		this.session = session;
	}

	public User getCurrentUser() {
		return currentUser;
	}

	public void setCurrentUser(User currentUser) {
		this.currentUser = currentUser;
	}

	public boolean isFormDis1() {
		return formDis1;
	}


	public void setFormDis1(boolean formDis1) {
		this.formDis1 = formDis1;
	}


	public int getId() {
		return id;
	}


	public void setId(int id) {
		this.id = id;
	}


	public String getName() {
		return name;
	}


	public void setName(String name) {
		this.name = name;
	}


	public String getLogin() {
		return login;
	}


	public void setLogin(String login) {
		this.login = login;
	}


	public String getPassword() {
		return password;
	}


	public void setPassword(String password) {
		this.password = password;
	}


	public String getEmail() {
		return email;
	}


	public void setEmail(String email) {
		this.email = email;
	}


	public List<User> getUsers() {
		return users;
	}


	public void setUsers(List<User> users) {
		this.users = users;
	}


	public List<String> getRest() {
		return rest;
	}


	public void setRest(List<String> rest) {
		this.rest = rest;
	}


	


	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public int getReclamationsApp() {
		return reclamationsApp;
	}

	public void setReclamationsApp(int reclamationsApp) {
		this.reclamationsApp = reclamationsApp;
	}

	public int getReclamationsRej() {
		return reclamationsRej;
	}

	public void setReclamationsRej(int reclamationsRej) {
		this.reclamationsRej = reclamationsRej;
	}
	
	
	
	
}

firstProject-web/src/main/webapp/pages/manager/home.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/templateManager/template.xhtml">
   <meta charset="utf-8"/>
      
     <meta charset="utf-8"/>
    <title>ConsomiTounsi</title>
      <!--Import Google Icon Font-->
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>
     
      <link type="text/css" rel="stylesheet" href="#{request.contextPath}/resources1/css/materialize.min.css"  media="screen,projection"/>

      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      
      <ui:define name="content">
 
    
</ui:define>
      
	
</ui:composition>

firstProject-web/src/main/webapp/pages/manager/listCommentaireRatings.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/templateManager/template.xhtml">
   <meta charset="utf-8"/>
      
     <meta charset="utf-8"/>
    <title>List  Users</title>
      <!--Import Google Icon Font-->
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>
     
      <link type="text/css" rel="stylesheet" href="#{request.contextPath}/resources1/css/materialize.min.css"  media="screen,projection"/>

      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      
      <ui:define name="content">

		  <h:form>
		  <a class='btn btn-primary' href='listCommentaires.jsf?id=#{commentaireRatingBean.idSujet}'> retour</a>
		  <div id="buttonBack"></div>
<table class="highlight centered  white lighten-2">
				    
				    <thead>
				    <th>id</th>
				    <th>reaction</th>
				    <th>utilisateur</th>
				    </thead>
				    <tbody id="dataSujet">
				    
				    </tbody>
	</table>
	
	
   
 <script type="text/javascript" src="#{request.contextPath}/resources1/js/jquery.min.js"></script>
      
      <script type="text/javascript" src="#{request.contextPath}/resources1/js/materialize.js"></script>
 <script>
 $(document).ready(function(){
    $('.modal').modal();
  });
 </script>
  <script >
$(document).ready(function(){
	var id = "#{commentaireRatingBean.idComm}"
	var idSujet = "#{commentaireRatingBean.idSujet}"
	  $.get('http://localhost:6587/api/SujetCommentaireAPI/getCommentairesRatings?id=' + id, function(data) {
		 var htmlContenu = '';
		 var link = 'listCommentaires.jsf?id=' + idSujet;
		 for(let obj of data) {
			  htmlContenu +=  "<tr><td>"+obj.id+"</td>"
			  + "<td>"+ obj.reaction +"</td>"
			  + "<td>"+ obj.email +"</td></tr>"
			  }
		  document.getElementById('dataSujet').innerHTML = htmlContenu;
	  });
	
});
	</script>
   </h:form>

	</ui:define>
      
	
</ui:composition>

firstProject-web/src/main/webapp/pages/manager/listCommentaires.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/templateManager/template.xhtml">
   <meta charset="utf-8"/>
      
     <meta charset="utf-8"/>
    <title>List  Users</title>
      <!--Import Google Icon Font-->
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>
     
      <link type="text/css" rel="stylesheet" href="#{request.contextPath}/resources1/css/materialize.min.css"  media="screen,projection"/>

      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      
      <ui:define name="content">

		  <h:form>
		  <a class="btn btn-primary" href="listSujets.jsf"> retour</a>
<table class="highlight centered  white lighten-2">
				    
				    <thead>
				    <th>id</th>
				    <th>contenu</th>
				    <th>date ajout</th>
				    <th>moyenne</th>
				    <th></th>
				    <th></th>
				    </thead>
				    <tbody id="dataSujet">
				    
				    </tbody>
	</table>
	
	
   
 <script type="text/javascript" src="#{request.contextPath}/resources1/js/jquery.min.js"></script>
      
      <script type="text/javascript" src="#{request.contextPath}/resources1/js/materialize.js"></script>
 <script>
 $(document).ready(function(){
    $('.modal').modal();
  });
 </script>
  <script >
$(document).ready(function(){
	var id = "#{commentaireBean.idSujet}";
	  $.get('http://localhost:6587/api/SujetCommentaireAPI/getCommentairesSujet?id=' + id, function(data) {
		 var htmlContenu = '';
		 for(let obj of data) {
			 console.log(obj);
			 var link = 'listCommentaireRatings.jsf?id='+ obj.id + '&amp;idSujet=' + obj.SujetId;
			 var link3 = 'supprimerCommentaire(' + obj.id + ')';
			 var link4 = '#';
			  htmlContenu +=  "<tr><td>"+obj.id+"</td>"
			  + "<td>"+ obj.content +"</td>"
			  + "<td>"+ obj.dateAjout +"</td>"
			  + "<td>"+obj.moyenne+"</td>"
			  + "<td><a href='+ link +'> voir ratings</a></td>"
			  + "<td><a onclick='+link3+' href='+link4+'> Supprimer</a></td></tr>";

			  }
		  document.getElementById('dataSujet').innerHTML = htmlContenu;
	  });
	
});
function supprimerCommentaire(idComm) {
	$.post('http://localhost:6587/api/SujetCommentaireAPI/DeleteCommentaire?id=' + idComm, function(data) {
		 document.location.reload(true);
	  });
}
	</script>
   </h:form>

	</ui:define>
      
	
</ui:composition>

firstProject-web/src/main/webapp/pages/manager/listReclamation.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/templateManager/template.xhtml">
   <meta charset="utf-8"/>
      
     <meta charset="utf-8"/>
    <title>List  Users</title>
      <!--Import Google Icon Font-->
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>
     
      <link type="text/css" rel="stylesheet" href="#{request.contextPath}/resources1/css/materialize.min.css"  media="screen,projection"/>

      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      
      <ui:define name="content">

		  <h:form>
<h:dataTable class="highlight centered  white lighten-2" value="#{userBean.allReclamation}" var="c"   >
				    
				    	<f:facet name="header" >All Reclamations</f:facet>
		<h:column filterBy="#{c.user_Reclame}" >
			<f:facet name="header">User Reclame </f:facet>
			<h:outputText value="#{c.user_Reclame}" />
		</h:column>
		<h:column>
			<f:facet name="header">Degres </f:facet>
			<h:outputText value="#{c.degres}" />
		</h:column>
			<h:column>
			<f:facet name="header">Description </f:facet>
			<h:outputText value="#{c.description}" />
		</h:column>
			<h:column>
			<f:facet name="header">Statut </f:facet>
			<h:outputText value="#{c.statut}" />
		</h:column>
			<h:column>
			<f:facet name="header">Type </f:facet>
			<h:outputText value="#{c.type}" />
		</h:column>
		<h:column>
			<f:facet name="header">User </f:facet>
			<h:outputText value="#{c.user.name}" />
		</h:column>
		
        <h:column>
			<f:facet name="header">action</f:facet>		
				<h:commandButton value="Approuver" actionListener="#{userBean.updateReclamation(c)}" styleClass="btn-small green accent-4" >	
				</h:commandButton>

		</h:column>
		<h:column>
			<f:facet name="header">action</f:facet>		
				<h:commandButton value="Rejeter" actionListener="#{userBean.rejeterReclamation(c)}" styleClass="btn-small red accent-4" >	
				</h:commandButton>

		</h:column>
	</h:dataTable>
	
	
   
 <script type="text/javascript" src="#{request.contextPath}/resources1/js/jquery.min.js"></script>
      
      <script type="text/javascript" src="#{request.contextPath}/resources1/js/materialize.js"></script>
 <script>
 $(document).ready(function(){
    $('.modal').modal();
  });
 </script>
 <script>
function cvBean.doDelete(c) {
    alert("Hello! I am an alert box!");
}
</script>
   </h:form>

	</ui:define>
      
	
</ui:composition>

firstProject-web/src/main/webapp/pages/manager/listUser.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/templateManager/template.xhtml">
   <meta charset="utf-8"/>
      
     <meta charset="utf-8"/>
    <title>List  Users</title>
      <!--Import Google Icon Font-->
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>
     
      <link type="text/css" rel="stylesheet" href="#{request.contextPath}/resources1/css/materialize.min.css"  media="screen,projection"/>

      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      
      <ui:define name="content">

		  <h:form>
<h:dataTable class="highlight centered  white lighten-2" value="#{userBean.allUser}" var="c"   >
				    
				    	<f:facet name="header" >All Users</f:facet>
		<h:column filterBy="#{c.name}" >
			<f:facet name="header">Name </f:facet>
			<h:outputText value="#{c.name}" />
		</h:column>
		<h:column>
			<f:facet name="header">Email </f:facet>
			<h:outputText value="#{c.email}" />
		</h:column>
		
		<h:column>
			<f:facet name="header">Statut </f:facet>
			<h:outputText value="#{c.statut}" />
		</h:column>
		
		
		
		
		
		
		
		<h:column>
			<f:facet name="header">action</f:facet>		
				<a href="reclamation.jsf?id=#{c.id}" class="btn btn-medium center-align"> Reclamer</a>


		</h:column>
	</h:dataTable>
	
	
   
 <script type="text/javascript" src="#{request.contextPath}/resources1/js/jquery.min.js"></script>
      
      <script type="text/javascript" src="#{request.contextPath}/resources1/js/materialize.js"></script>
 <script>
 $(document).ready(function(){
    $('.modal').modal();
  });
 </script>
 <script>
function cvBean.doDelete(c) {
    alert("Hello! I am an alert box!");
}
</script>
   </h:form>

	</ui:define>
      
	
</ui:composition>